Imports System.Text

Public Class MapForDirections

    Property OriginLatLng As MapLatLng
    Property DestinationLatLng As MapLatLng

    Public Function GetHtml() As String
        Dim sb = New StringBuilder()
        sb.AppendLine("// Javascript generated by MapForDirections.GetHtml:")
        sb.AppendLine("var map = new MapForDirections();")
        sb.AppendLine("map.origin = " + OriginLatLng.GetJs() + ";")
        sb.AppendLine("map.destination = " + DestinationLatLng.GetJs() + ";")
        sb.AppendLine("map.initialize();")
        Dim js = sb.ToString()
        Dim html = My.Resources.GoogleMapsHtml.Replace("##JAVASCRIPT-TO-INITIALIZE-MAPPING##", js)
        Return html
    End Function

End Class
