Imports System.Text

Public Class MapForGeocoding

    Property FindByAddress As String
    Property FindByLatLng As MapLatLng

    Public Function GetHtml() As String
        Dim sb = New StringBuilder()
        sb.AppendLine("// Javascript generated by MapForGeocoding.GetHtml:")
        sb.AppendLine("var map = new MapForGeocoding();")
        If FindByAddress IsNot Nothing Then
            sb.AppendLine("map.address = '" + MapScriptingObject.EscapeSingleQuotes(FindByAddress) + "';")
        End If
        If FindByLatLng IsNot Nothing Then
            sb.AppendLine("map.addressLatLng = " + FindByLatLng.GetJs() + ";")
        End If
        sb.AppendLine("map.initialize();")
        Dim js = sb.ToString()
        Dim html = My.Resources.GoogleMapsHtml.Replace("##JAVASCRIPT-TO-INITIALIZE-MAPPING##", js)
        Return html
    End Function

End Class
