Public Class MapForGeocoding

    Property FindByAddress As String
    Property FindByLatitude As Double?
    Property FindByLongitude As Double?

    Public Function GetHtml() As String
        Dim lines As String() = {
            "// Javascript generated by MapForGeocoding.GetHtml:",
            "var map = new MapForGeocoding();",
            "map.address = '" + If(FindByAddress, "").Replace("'", "\'") + "';",
            "map.initialize();"
        }
        Dim js = String.Join(Environment.NewLine, lines)
        Dim html = My.Resources.GoogleMapsHtml.Replace("##JAVASCRIPT-TO-INITIALIZE-MAPPING##", js)
        Return html
    End Function

End Class
